---
- hosts: none
  become: yes
  roles:
    - { role: geerlingguy.nginx }
    - af-syslog
    - role: geerlingguy.java
      java_packages:
        - java-1.8.0-openjdk-devel
    - sbt
    - { role: geerlingguy.git }
    - af-web
- hosts: woop.ac
  become: yes
  roles:
    # - { role: geerlingguy.git }
    - { role: af-server, app_port: 7654 }
    - { role: af-server, app_port: 30000 }
    - { role: af-server-deploy }

- hosts: odin
  become: yes
  roles:
    - { role: af-user-sync }