---
- hosts: none
  become: yes
  roles:
    - { role: geerlingguy.nginx }
    - af-syslog
    - role: geerlingguy.java
      java_packages:
        - java-1.8.0-openjdk-devel
    - sbt
    - { role: geerlingguy.git }
    - af-web
- hosts: woop.ac
  become: yes
  roles:
    # - { role: geerlingguy.git }
    # - { role: af-server, app_port: 7654 }
    # - { role: af-server, app_port: 30000 }
    # - { role: af-server-deploy }
    # - { role: ac-sync-blacklist }
    - { role: ac-private-server, app_port: 1999 }
    - { role: ac-private-server, app_port: 2999 }
    - { role: ac-private-server, app_port: 3999 }
    - { role: ac-private-server, app_port: 4999 }
    # - { role: ac-public-server, app_port: 10000 }
    - { role: ac-public-server, app_port: 28763 }

- hosts: califa
  become: yes
  roles:
    # - { role: geerlingguy.repo-epel } <- weird. screws up node install
    # - geerlingguy.nodejs
    # - { role: geerlingguy.git }
    # - { role: af-server, app_port: 7654 }
    # - { role: af-server, app_port: 30000 }
    # - role: ac-sync-blacklist
    #   blacklist_user: califac
    #   blacklist_target: /home/califac/assaultcube/config
    - role: geerlingguy.nginx
      nginx_vhosts:
        - listen: "80"
          server_name: "califa.actionfps.com"
          state: "present"
          extra_parameters: |
            location /demos/ {
              autoindex on;
              alias /home/califac/assaultcube/demos/;
            }

 #   - geerlingguy.nodejs
 #   - { role: af-server-deploy }

- hosts: odin
  become: yes
  roles:
    - { role: af-user-sync }
    # - { role: af-ladder-read }