- name: Set up af user
  user:
    name: af

- name: copy systemd service template configuration
  template: >
    src=af-web.service.j2
    dest=/etc/systemd/system/af-web.service
    mode=0755
  register: af_web_unit

- name: reload systemd
  systemd:
    name: af-web
    daemon_reload: yes
  when: af_web_unit.changed

- name: restart and enable the service
  systemd:
    name: af-web
    state: restarted
    enabled: yes
  when: af_web_unit.changed
